[toolchain]
[Rust ^1.60 + Cargo](https://www.rust-lang.org/tools/install)
With the WASM target installed: `rustup target add wasm32-unknown-unknown`
 [cargo-make](https://crates.io/crates/cargo-make): `cargo install cargo-make`
[Node.js](https://nodejs.org/)
channel = "1.65"
